version: "3"
services:
  #external-system-server
  zookeeper:
    image: 'zookeeper:3.9.2'
    networks:
      - "lucycato_network"
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none
  kafka:
    image: 'wurstmeister/kafka:2.13-2.8.1'
    networks:
      - "lucycato_network"
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LC
      - KAFKA_LISTENERS=LC://kafka:29092,LX://localhost:9092
      - KAFKA_ADVERTISED_LISTENERS=LC://kafka:29092,LX://localhost:9092
    depends_on:
      - zookeeper
    #kafka topic create
    # - enter kafka terminal -> kafka-topics.sh --create --bootstrap-server <broker-list> --replication-factor <number> --partitions <number> --topic <topic-name>
    # - ex) kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 3 --topic my-topic
    #kafka topic list
    # - enter kafka terminal -> kafka-topics.sh --list --bootstrap-server <broker-list>
    # - ex) kafka-topics.sh --list --bootstrap-server localhost:9092
    #kafka topic delete
    # - enter kafka terminal -> kafka-topics.sh --delete --bootstrap-server <broker-list> --topic <topic-name>
    # - ex) kafka-topics.sh --delete --bootstrap-server localhost:9092 --topic my-topic
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - "lucycato_network"
    ports:
      - "8989:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  #infra-server
  gateway-server:
    image: lucycato/lucycato-e-commerce-gateway-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8060:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  config-server:
    image: lucycato/lucycato-e-commerce-config-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8061:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  eureka-server:
    image: lucycato/lucycato-e-commerce-eureka-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8062:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  #operate-server
  logging-consumer:
    image: lucycato/lucycato-e-commerce-logging-consumer:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8070:8080"
#      - "5005:5005"
    environment:
#      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  task-consumer:
    image: lucycato/lucycato-e-commerce-task-consumer:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8071:8080"
    environment:
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql:3306/default
      - SPRING_R2DBC_USERNAME=admin
      - SPRING_R2DBC_PASSWORD=password
  auth-server:
    image: lucycato/lucycato-e-commerce-auth-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8072:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  #Service
  user-service:
    image: lucycato/lucycato-e-commerce-user-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/default
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
  notification-service:
    image: lucycato/lucycato-e-commerce-notification-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8081:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  product-service:
    image: lucycato/lucycato-e-commerce-product-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8082:8080"
    environment:
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql:3306/default
      - SPRING_R2DBC_USERNAME=admin
      - SPRING_R2DBC_PASSWORD=password

networks:
  lucycato_network:
    driver: bridge

