version: "3"
services:
  #external-system-server
  zookeeper:
    image: 'arm64v8/zookeeper:3.8'
    networks:
      - positeam_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none
  kafka:
    image: 'wurstmeister/kafka:2.13-2.8.1'
    networks:
      - positeam_network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LC
      - KAFKA_LISTENERS=LC://kafka:29092,LX://localhost:9092
      - KAFKA_ADVERTISED_LISTENERS=LC://kafka:29092,LX://localhost:9092
    depends_on:
      - zookeeper
    #kafka topic create
    # - enter kafka terminal -> kafka-topics.sh --create --bootstrap-server <broker-list> --replication-factor <number> --partitions <number> --topic <topic-name>
    # - ex) kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 3 --topic my-topic
    #kafka topic list
    # - enter kafka terminal -> kafka-topics.sh --list --bootstrap-server <broker-list>
    # - ex) kafka-topics.sh --list --bootstrap-server localhost:9092
    #kafka topic delete
    # - enter kafka terminal -> kafka-topics.sh --delete --bootstrap-server <broker-list> --topic <topic-name>
    # - ex) kafka-topics.sh --delete --bootstrap-server localhost:9092 --topic my-topic
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - positeam_network
    ports:
      - "8989:8080"
    restart: always
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  #infra-server
  gateway-server:
    image: lucycato/big-tech-gateway-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8060:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  config-server:
    image: lucycato/big-tech-config-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8061:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  eureka-server:
    image: lucycato/big-tech-eureka-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8062:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  #operate-server
  logging-consumer:
    image: lucycato/big-tech-logging-consumer:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8070:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  task-consumer:
    image: lucycato/big-tech-task-consumer:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8071:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  auth-server:
    image: lucycato/big-tech-auth-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8072:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  batch-server:
    image: lucycato/big-tech-batch-server:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8073:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  #Service
  member-service:
    image: lucycato/big-tech-member-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  notification-service:
    image: lucycato/big-tech-notification-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8081:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  event-service:
    image: lucycato/big-tech-event-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8082:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  delivery-service:
    image: lucycato/big-tech-delivery-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8083:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout
  webtoon-service:
    image: lucycato/big-tech-webtoon-service:1.0.0
    networks:
      - "lucycato_network"
    ports:
      - "8084:8080"
    environment:
      - KAFKA_LOGGING_TOPIC=lucycato.bigtech.logging.out.stdout

networks:
  lucycato_network:
    driver: bridge

